print("Covariate Descriptions:
STRM_ORDER	Strahler stream order
StrmSlope	Channel gradient within the reach
MaxGradD	Maximum gradient downstream of the stream reach 
WidthM	Stream width (m)
OUT_DIST	Distance from stream reach to ocean via stream network
CLASS_Rank	Hydrologic Landscape Class ranked by suitability for coho (see below)
StrmPow	Stream Power: channel slope multiplied by drainage area (km2)
MAnnSed	Annual sediment averaged over the 12-digit hydrologic unit (sub-watershed)
Barriers	Number of barriers below the stream reach
SolMean	Mean solar irradiance (Terrian Works; see below)
IP_COHO	Intrinsic Potential for coho winter rearing habitat (see below)
MWMT_Index	Maximum Weekly Mean Temperature (NorWest 93-11) indexed by annual PRISM July mean air temperature (see below)
W3Dppt	Annual maximum of the moving three-day sum of PRISM precipitation
SprPpt	Annual sum of PRISM precipitation during the spring season (annual)

CLASS_Rank:  Five indices were combined to characterize hydrologic landscape classifications: climate (very wet, wet, moist, dry, semiarid, and arid based on the Feddema (2005) Moisture Index), runoff seasonality (winter, spring or summer), aquifer permeability (low, moderate, or high), terrain (mountainous, flat, or transitional), and soil permeability (low, moderate, or high). See Leibowitz et al. 2016 for more detail.  We ranked these classifications based on assumptions about characteristics that would be most advantageous to coho salmon (very wet or wet>moist>others, winter runoff>spring runoff, most sites are in mountainous or transitional terrain, the coast tends to have low aquifer permeability and high soil permeability).
Intrinsic Potential: Intrinsic potential to support coho salmon is expressed as the geometric mean of classified channel gradient, valley constraint, and mean annual discharge (see table below for classifications for coho).  See Burnett et al. 2003 and Burnett et al. 2007 for more details.
 
 
SolMean: SolMean is an estimate of the current solar thermal energy reaching the stream reach.  The calculation of the effects of vegetative shading on streams and rivers begins with a calculation of bare earth radiation (how much solar radiation would reach the site with no shade). This parameter is predicted by NetMap's Thermal Load Sensitivity Tool. Bare earth radiation into streams (watt-hours/m2) is controlled by the solar angle, the time of year, channel width, channel orientation (azimuth) and topographic shading.  To learn more see NetMap's "Thermal Load Sensitivity" tool.  There are different methods to predict how stream side vegetation results in shade. NetMap uses a model that incorporates vegetation basal area and tree height (Groom et al. 2011). The empirically based, statistical model developed in coastal Oregon predicts that percent shade in positively correlated to basal area (e.g., the denser the vegetation the greater the shade) but inversely related to tree height (the taller the trees, the less shade). This rather non intuitive inverse relationship between tree height and shade appears reasonable if one considers that as trees grow taller, as in a conifer forest that is mature or very old, there are more open canopies and less along-stem vegetation. Conversely, with shorter vegetation, canopies can be closer together and there may be greater along-stream vegetation. However, it is important to keep in mind that the shadow cast by taller trees (the area of a stream that is affected by shade) increases with vegetation height.  
MWMT_Index:  This index combines the NorWest historical composite scenario representing the 19-year average Maximum Weekly Maximum Temperature (MWMT or 7DADM) for 1993-2011, with annual estimates of July mean air temperature from the PRISM Climate Group (USDA).  PRISM air temperature data are modeled using climatologically-aided interpolation (CAI) of observations at weather stations to provide landscape coverage of climate variables.  Values of PRISM July air temperature for the years 1993-2011 were averaged and then the values for each year in the study time period (1996-2020) were divided by this average providing a ratio for each year relative to average conditions.  This proportion was then multiplied by the 1993-2011 NorWest estimate of MWMT to provide annual variation around this average.  
Burnett, K.; Reeves, G; Miller, D; Clarke, S.; Christiansen, K; Vance-Borland, K. 2003. A first step toward broad-scale identification of freshwater protected areas for Pacific salmon and trout in Oregon, USA. In: Beumer, J.P.; Grant, A; Smith, D.C., eds. Aquatic protected areas: What works best and how do we know? Proceedings of the world congress on aquatic protected areas, Cairns, Australia, North Beach, WA, Australia: Australian Society for Fish Biology. 
Burnett, K.; Miller, D.; Reeves, G.; Spies, T.; Clarke, S.; Vance-Borland, K.; Christiansen, K. 2007. Distribution of salmon habitat potential in the coastal province of Oregon.
Leibowitz , S.G., Comeleo, R.L.; Wigington, P.J.; Weber, M.H.; Sproles, E.A.; Sawicz K.A. 2016. Hydrologic Landscape Characterization for the Pacific Northwest, USA. JAWRA: volume 52 pp. 473-493.
")